### PR TITLE
change package name from urdf_realtime_filter to realtime_urdf_filter

### PR DESCRIPTION
**Pull request by mmurooka**

### CODE REVIEW

**Comment by mmurooka** [comment]
Is urdf_realtime_filter mistaken?
The name of github repository[1] and roswiki title[2] are realtime_urdf_filter.
[1] https://github.com/blodow/realtime_urdf_filter
[2] http://wiki.ros.org/realtime_urdf_filter

**Comment by JimmyDaSilva** [comment]
@mmurooka There is a bunch of things that need to be fixed that have already been discussed and done.
You should check other people's commit on there forks, and especially the existing pull requests.
On PR #9, mintar and I have made a couple of interesting modifications.

**Comment by mmurooka** [comment]
Sorry. Thank you.
Why don't you merge https://github.com/blodow/realtime_urdf_filter/pull/9?

**Comment by JimmyDaSilva** [comment]
We would love to do so but we don't own the package, @blodow does, and he hasn't been active on this for quite a long time.

**Comment by JimmyDaSilva** [comment]
@mmurooka PR #9 has been merged last night :)

**Pull request closed without merging**
